//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXFIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CARNET { get; set; }
        public Nullable<int> IDCURSO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual CURSO CURSO { get; set; }
    }
}
